pipeline {
    agent any

    stages {
        stage('Clone Repo') {
            steps {
                git credentialsId: 'github-creds', url: 'https://github.com/d-madiou/alx-backend-python.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                script { // Use a script block to access the tool step
                    def pythonHome = tool 'Python3' // Get the path to your Python installation
                    env.PATH = "${pythonHome}/bin:${env.PATH}" // Add Python to PATH

                    // Now you can use pip as usual
                    sh 'pip install -r messaging_app/requirements.txt'
                }
            }
        }

        stage('Run Tests') {
            steps {
                script { // Use a script block for tests if Python is only added in previous stage
                    // If you added Python to PATH in a previous script block, it should be available
                    sh 'pytest messaging_app/tests/ --junitxml=report.xml'
                }
            }
        }

        stage('Archive Test Report') {
            steps {
                junit 'report.xml'
            }
        }
    }
}