# Generated by Django 5.2.3 on 2025-06-14 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_alter_message_options_alter_messagehistory_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='messagehistory',
            options={},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='messaging_m_receive_6da6d1_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='messaging_m_sender__12c98b_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='messaging_m_parent__e699d7_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='messaging_n_user_id_bd7d88_idx',
        ),
        migrations.AddField(
            model_name='conversation',
            name='participants',
            field=models.ManyToManyField(related_name='conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messaging.conversation'),
        ),
    ]
